name: publish

on:
  push:
    tags:
      - "edumfa-*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
       REGISTRY: "ghcr.io"
       REPOSITORY: "oci://ghcr.io/aleyna72072/helm-charts"
       GHCR_REPOSITORY: "aleyna72072/helm-charts/edumfa"
    steps:
      - uses: actions/checkout@v7
      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.12.0
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package and publish chart
        run: |
          set -euo pipefail
          git_tag="${{ github.ref_name }}"
          git_tag_prefix="edumfa-"
          git_tag_version=${git_tag#"$git_tag_prefix"}
          chart_version="$(yq '.version' ./charts/edumfa/Chart.yaml)"

          # If the git tag and the chart version is not equal, abort.
          if [ "$git_tag_version" != "$chart_version" ]; then
            echo "Git tag and chart version have unequal version. Aborting.."
            exit 1
          fi

          # Helm and GHCR do not currently allow immutable tags/no overwriting
          # existing ones. Check tediously if the chart version already exists.
          # Abort if so.
          ghcr_token=$(curl -s "https://ghcr.io/token?scope=repository:${{ env.GHCR_REPOSITORY }}:pull" | jq -r .token)
          # this is either "false" or "true"
          has_version=$(curl -s -H "Authorization: Bearer $ghcr_token" "https://ghcr.io/v2/${{ env.GHCR_REPOSITORY }}/tags/list" | jq "any(.tags[]; . == \"${chart_version}\")")
          if [ "$has_version" != "false" ]; then
            echo "Version $chart_version already exists. Aborting..."
            exit 2
          fi

          helm package ./charts/edumfa/
          helm push edumfa*.tgz ${{ env.REPOSITORY  }}
      - name: GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          body: "See https://github.com/eduMFA/helm-charts/blob/main/charts/edumfa/CHANGELOG.md for the changelog."
          working_directory: ./charts/edumfa/
          files: values.yaml
